### ISSUE TITLE
Feat: move chain specific logic to importable submodule

### ISSUE THREAD

**Issue by Seth-Schmidt** [PowerLoom/pooler#100]
**Is your feature request related to a problem?**
The introduction of non-Ethereum based use cases has caused divergence in the branches of `pooler`, where each chain's use cases require their own branch. Additionally, pooler requires a separate branch for use cases depending on their use of Uniswap V2 or Uniswap V3 smart contracts and pair addresses. This divergence has caused implementing feature updates and performing maintenance across use cases more difficult than it needs to be. 

**Describe the solution you'd like**
These chain specific components should be moved to a separate submodule (e.g. `chain_utils`) to be imported on demand for each chain. This will allow every use case to share the same pooler version, while still allowing for changes to be made for chain specific issues. 

**Describe alternatives you've considered**
I've considered moving chain specific logic to the `compute` module of each use case, but this will only create a dependency that each compute module will need to meet and is unnecessary. 

**Additional context**
N/A

**Comment by xadahiya** [comment]
Implemented in https://github.com/PowerLoom/snapshotter-core/pull/10
