### ISSUE TITLE
Node recovery and diagnostics

### ISSUE THREAD

**Issue by anomit** [PowerLoom/pooler#47]
**Is your feature request related to a problem?**

Presently, the pre-testnet and testnet participants have been running into a recurring issue on their hosted node instances where the virtualized host OS kills off long running processes silently, specifically on the `pooler` repo. This has been affecting the snapshot builder processes spawned from the [process_hub_core](https://github.com/PowerLoom/pooler/blob/main/snapshotter/process_hub_core.py) which results in no epochs being processed and no snapshots being submitted once the processes get killed off.

The [existing respawn feature](https://github.com/PowerLoom/pooler/blob/f344e2f9fb743c6c0d8346dde0acf9f006b4da85/snapshotter/process_hub_core.py#L80-L187) on crashed worker processes does not kick in since such processes are terminated by delivering a `SIGKILL` signal which can not be handled.

The current diagnostics available at the moment are the following 

* [worker processes status report script](https://github.com/PowerLoom/pooler/blob/testnet_pretask/worker_process_report.py)
* [snapshotter internal APIs on epoch processing status](https://github.com/PowerLoom/pooler/blob/testnet_pretask/README.md#internal-snapshotter-apis)

which do not give an immediate actionable insight or hook to restore the node to a working state.

At the moment someone has to monitor the snapshotter submissions on the latest epochs on the consensus dashboard against their node's identity to be aware of such an issue.

**Describe the solution you'd like**
* Worker processes should be respawned automatically based on internal health checks performed by the core on itself
* Improve the [CLI used to interact with process_hub_core ](https://github.com/PowerLoom/pooler/blob/testnet_pretask/snapshotter/processhub_cmd.py)
  * better view of node health 
  * command for a clean respawn of the worker processes

**Describe alternatives you've considered**

A quickfix would have been to add auto-restarts in a cron script or timed shell script, but such an approach will be non-deterministic and violates the clearly defined state transitions of the protocol that the node participates.

**Additional context**

NA

**Comment by xadahiya** [comment]
Implemented in #50, #53 and #55.
