### ISSUE TITLE
Integrate IPFS and web3 storage uploads

### ISSUE THREAD

**Issue by anomit** [PowerLoom/pooler#52]
**Is your feature request related to a problem?**
Presently, snapshotters send the entire contents of each snapshot to the [payload commit service](https://github.com/PowerLoom/audit-protocol/blob/main/docs/Introduction.md#payload-commit-service) in audit protocol over RabbitMQ. This is a huge overhead considering that this can take place for thousands of projects per epoch. This often causes high resource usage when there is a burst of large snapshots that are computed.

**Describe the solution you'd like**
Once the snapshots are computed and built, upload them from within the snapshot and aggregation workers itself.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by xadahiya** [comment]
Implemented in #53 and #55, closing.
