### ISSUE TITLE
Uniswap v3 completion

### ISSUE THREAD

**Issue by getjiggy** [PowerLoom/pooler#54]
# Base Snapshots

Pair reserves snapshot
- Token0 Price
- Token1 Price 
- TVL (different from reserves)
- TVL in USD? (needed only if TVL is not in USD)

Trade Volume Snapshot (Mint and burn are slightly different for v3)
- Token0 trade volume
- Token0 trade volume (USD)
- Token1 trade volume
- Token1 trade volume (USD)
- Total Fees (USD)
- Total Trades (USD)

# Aggregate Snapshots
- 24h trade volume (same as v2)
- 7d trade volume (save as v2)
- Top pairs (same as v2)
- Top tokens (same as v2)

# Aggregates for Graphs (to be done later)
- TVL over time (continuous aggregate of total TVL over time (can be from top tokens or top pairs)) [Just add graph data points on each epoch]
- Volume over time (continuous aggregate of total volume over time (can be from top tokens or top pairs)) [Just add graph data points on each epoch]
- Token graphs (Volume, TVL, Price) - Can come from aggregating Top Tokens snapshots over time
- Pair graphs (Volume, Liquidity, Fees) - Volume and Fees are simple enough can be done just like token graphs. Liquidity spread graph is a little tricky and will need a bit of research for calculation. Once base snapshot is there then we can just listen for Add/Remove events and update values accordingly

Building Uniswap exact dashboard replica won't be enough we need to make our dashboard better and more details so people can start using our dashboard. Will help in our vampire attack later.

* Liquidity Spread and TVL calculation are parts of the same problem

- Token price calculation in Python - https://gist.github.com/xadahiya/98beea001a37eb1042f8c08e9bed0389

**Comment by kanikamishra** [comment]
We are moving it to next iteration.
