### ISSUE TITLE
Core-api /internal/snapshotter/status endpoint does not return the correct status report

### ISSUE THREAD

**Issue by Seth-Schmidt** [PowerLoom/pooler#71]
## Describe the bug 
Calling the `/internal/snapshotter/status` endpoint always returns:

> {"totalSuccessfulSubmissions":0,"totalIncorrectSubmissions":0,"totalMissedSubmissions":0,"projects":[]}

The individual projects' submission statuses are correctly saved in redis, but there is an issue with retrieval. 

## To Reproduce
**Affected versions**: all

1. call `/internal/snapshotter/status` on any running node
2. 
3.

**Expected behavior**
The endpoint should return return the total successful, incorrect, and missed snapshots for all projects

**Proposed Solution**
The [redis data request](https://github.com/PowerLoom/pooler/blob/5826745cd0354e0e4687d4d9d3192a741feeabe9/snapshotter/utils/data_utils.py#L643) in `utils.data_utils.get_snapshotter_status` should use the destructured projects list.

**Additional context**
Using python 3.10.13, redis:alpine 7.2.4 docker image, and redis 4.6.0 python library

**Comment by Seth-Schmidt** [comment]
Redis data retrieval is fine. All projects are never stored in the `storedProjectIds` set, so the mget returns nothing.

**Comment by anomit** [comment]
The solution would be to get the projects list from the projects config, and then load the epoch transition results accordingly

**Comment by Seth-Schmidt** [comment]
Added the necessary changes in #74

**Comment by Seth-Schmidt** [comment]
Closed with #74
