### ISSUE TITLE
core-api /internal/snapshotter/status/{project_id} endpoint validation error

### ISSUE THREAD

**Issue by Seth-Schmidt** [PowerLoom/pooler#72]
## Describe the bug 
Calling /internal/snapshotter/status/{project_id} for a given project can fail due to a validation error for the `SnapshotterStatusReport` model. 

The `SnapshotterReportState` enum for `SnapshotterStatusReport.state` does not account for the ONLY_FINALIZED_SNAPSHOT_RECIEVED state that can be cached by [audit-protocol](https://github.com/PowerLoom/audit-protocol/blob/5d39e1643f4b4e8e05cff34844506545e221fe77/go/goutils/datamodel/data_model.go#L10).

## To Reproduce
**Affected versions**: nms_master

1. start a test node
2. docker exec into the running redis instance: `docker exec -it <redis-container> redis-cli`
3. add an example audit-protocol [status report](https://github.com/PowerLoom/audit-protocol/blob/main/go/payload-commit/service/service.go#L303-L308) to redis: 

`HSET projectID:poolContract_total_supply:0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48:aavev3:snapshotterStatusReport 1 "{\"submittedSnapshotCid\":\"\",\"finalizedSnapshotCid\":\"abc\",\"state\":\"ONLY_FINALIZED_SNAPSHOT_RECIEVED\",\"reason\":\"OnlyfinalizedCIDreceived\"}"`

4. close redis or open another terminal and call the internal snapshotter status endpoint for the example project:

`curl -L -X GET 'http://localhost:8002/internal/snapshotter/status/poolContract_total_supply:0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48:aavev3' \
-H 'Accept: application/json'`

**Expected behavior**
The endpoint should return the project status report.

**Proposed Solution**
Add the "ONLY_FINALIZED_SNAPSHOT_RECIEVED" status to the `SnapshotterReportState` enum

**Comment by xadahiya** [comment]
Fixed in #73
