### ISSUE TITLE
Add snapshotter identity check to devnet branch

### ISSUE THREAD

**Issue by Seth-Schmidt** [PowerLoom/pooler#90]
We need to update the snapshotter_id_ping.py script to enable Snapshot slot checks. Currently, this feature is disabled in the testnet, but we want to make sure our system accurately checks if Snapshotting is allowed for the given instance ID.

- [x] The script should check if Snapshotting is allowed for the given instance ID.
- [x] Based on the result of the query, set the active status key in Redis.
- [x] Ensure the script handles any potential exceptions and exits with the correct status code.

- [x] https://github.com/PowerLoom/pooler/pull/91

**Comment by xadahiya** [comment]
Implemented in https://github.com/PowerLoom/pooler/pull/91, closing.
